version: '2'
services:
  db:
    image: mongo:3.0.2
    volumes:
      - ./mongodb:/data/db
      - ./mongodb_config:/data/configdb
    network_mode: bridge
  product:
    build: ./src
    volumes:
      - ./src:/app/src
      - ./src/package.json:/app/package.json
      - ./src/node_modules:/app/node_modules
    links:
      - db
    depends_on:
      - db
    ports:
      - "3000:3000"
    network_mode: bridge